module.exports.prods=[
    {
        artName: 'Sunset Splendor',
        description: 'A breathtaking painting capturing the beauty of a sunset over the mountains.',
        price: 'Rs. 350.00',
        category: 'Painting',
        creationDate: '2023-01-15',
        listedBy: 'Artist123',
        image: 'sunset_splendor.jpg',
    },
    {
        artName: 'Abstract Harmony',
        description: 'An abstract artwork that explores the harmony of colors and shapes.',
        price: 'Rs. 180.00',
        category: 'Painting',
        creationDate: '2022-11-28',
        listedBy: 'CreativeMind',
        image: 'abstract_harmony.jpg',
    },
    {
        artName: 'Sculpture of Serenity',
        description: 'A serene sculpture crafted from marble, emanating tranquility and elegance.',
        price: 'Rs. 500.00',
        category: 'Sculpture',
        creationDate: '2023-02-05',
        listedBy: 'SculptorArtisan',
        image: 'serenity_sculpture.jpg',
    },
    {
        artName: 'Oceanic Dream',
        description: 'A mesmerizing seascape that captures the essence of the deep blue ocean.',
        price: 'Rs. 280.00',
        category: 'Painting',
        creationDate: '2023-03-10',
        listedBy: 'SeaDreamer',
        image: 'oceanic_dream.jpg',
    },
    {
        artName: 'Urban Reflections',
        description: 'Photographic reflections of cityscapes capturing the hustle and bustle of urban life.',
        price: 'Rs. 120.00',
        category: 'Sketches',
        creationDate: '2022-12-18',
        listedBy: 'CityExplorer',
        image: 'urban_reflections.jpg',
    },
    {
        artName: 'Whimsical Woodwork',
        description: 'Handcrafted wooden sculptures that bring a touch of whimsy to any space.',
        price: 'Rs. 220.00',
        category: 'Sketches',
        creationDate: '2023-01-02',
        listedBy: 'WoodArtisan',
        image: 'whimsical_woodwork.jpg',
    },
    {
        artName: 'Ethereal Elegance',
        description: 'An ethereal digital artwork that blends fantasy and elegance seamlessly.',
        price: 'Rs. 150.00',
        category: 'Painting',
        creationDate: '2023-02-20',
        listedBy: 'DigitalDreamer',
        image: 'ethereal_elegance.jpg',
    },
    {
        artName: 'Rustic Realism',
        description: 'Realistic paintings capturing the rustic beauty of rural landscapes.',
        price: 'Rs. 300.00',
        category: 'Painting',
        creationDate: '2022-11-05',
        listedBy: 'RuralRealist',
        image: 'rustic_realism.jpg',
    },
    {
        artName: 'Cinematic Splendor',
        description: 'Photographic prints capturing cinematic moments from around the world.',
        price: 'Rs. 200.00',
        category: 'Sculptures',
        creationDate: '2023-03-05',
        listedBy: 'CinephileShutterbug',
        image: 'cinematic_splendor.jpg',
    },
    {
        artName: 'Whispering Winds',
        description: 'Abstract paintings inspired by the whispers of the wind through nature.',
        price: 'Rs. 160.00',
        category: 'Painting',
        creationDate: '2023-01-28',
        listedBy: 'NatureWhisperer',
        image: 'whispering_winds.jpg',
    },
    {
        artName: 'Cerulean Serenade',
        description: 'A ceramic sculpture in serene shades of blue, evoking a calming melody.',
        price: 'Rs. 450.00',
        category: 'Sculpture',
        creationDate: '2022-12-10',
        listedBy: 'CeramicArtisan',
        image: 'cerulean_serenade.jpg',
    },
    {
        artName: 'Galactic Vision',
        description: 'Digital art exploring galactic landscapes and cosmic visions.',
        price: 'Rs. 180.00',
        category: 'Sketches',
        creationDate: '2023-02-15',
        listedBy: 'CosmicDreamer',
        image: 'galactic_vision.jpg',
    },
    {
        artName: 'Enchanting Engravings',
        description: 'Intricate engravings on various materials that enchant the observer.',
        price: 'Rs. 250.00',
        category: 'Sculpture',
        creationDate: '2023-03-20',
        listedBy: 'EngravingArtisan',
        image: 'enchanting_engravings.jpg',
    },
    {
        artName: 'Vibrant Vistas',
        description: 'Paintings bursting with vibrant colors, depicting scenic landscapes.',
        price: 'Rs. 280.00',
        category: 'Painting',
        creationDate: '2023-01-12',
        listedBy: 'ColorfulCanvas',
        image: 'vibrant_vistas.jpg',
    },
    {
        artName: 'Whimsical Watercolors',
        description: 'Delicate watercolor paintings that bring whimsy and charm to any space.',
        price: 'Rs. 130.00',
        category: 'Painting',
        creationDate: '2022-12-28',
        listedBy: 'WatercolorDreamer',
        image: 'whimsical_watercolors.jpg',
    },
    {
        artName: 'Astral Abstractions',
        description: 'Abstract digital artworks inspired by the astral realm and cosmic energies.',
        price: 'Rs. 200.00',
        category: 'Sketches',
        creationDate: '2023-02-28',
        listedBy: 'AstralArtisan',
        image: 'astral_abstractions.jpg',
    },
    {
        artName: 'Rustic Reflections',
        description: 'Photographic prints reflecting the rustic charm of countryside life.',
        price: 'Rs. 150.00',
        category: 'Sketches',
        creationDate: '2023-03-15',
        listedBy: 'RuralExplorer',
        image: 'rustic_reflections.jpg',
    },
    {
        artName: 'Celestial Ceramics',
        description: 'Ceramic sculptures inspired by celestial bodies and cosmic aesthetics.',
        price: 'Rs. 350.00',
        category: 'Sculpture',
        creationDate: '2023-01-20',
        listedBy: 'CelestialArtisan',
        image: 'celestial_ceramics.jpg',
    },
    {
        artName: 'Mystical Murals',
        description: 'Large-scale murals that transport observers to mystical realms.',
        price: 'Rs. 500.00',
        category: 'Sculpture',
        creationDate: '2022-11-15',
        listedBy: 'MuralistMaster',
        image: 'mystical_murals.jpg',
    }
];