module.exports.prods=[
    {
        artName: 'Sunset Splendor',
        description: 'A breathtaking painting capturing the beauty of a sunset over the mountains.',
        price: 350.00,
        category: 'Painting',
        creationDate: '2023-01-15',
        listedBy: 'Artist123',
        image: 'painting1.jpg',
    },
    {
        artName: 'Abstract Harmony',
        description: 'An abstract artwork that explores the harmony of colors and shapes.',
        price: 180.00,
        category: 'Painting',
        creationDate: '2022-11-28',
        listedBy: 'CreativeMind',
        image: 'painting2.jpg',
    },
    {
        artName: 'Sculpture of Serenity',
        description: 'A serene sculpture crafted from marble, emanating tranquility and elegance.',
        price: 500.00,
        category: 'Sculpture',
        creationDate: '2023-02-05',
        listedBy: 'SculptorArtisan',
        image: 'sculpture1.jpg',
    },
    {
        artName: 'Oceanic Dream',
        description: 'A mesmerizing seascape that captures the essence of the deep blue ocean.',
        price: 280.00,
        category: 'Painting',
        creationDate: '2023-03-10',
        listedBy: 'SeaDreamer',
        image: 'painting3.jpg',
    },
    {
        artName: 'Urban Reflections',
        description: 'Photographic reflections of cityscapes capturing the hustle and bustle of urban life.',
        price: 120.00,
        category: 'Sketches',
        creationDate: '2022-12-18',
        listedBy: 'CityExplorer',
        image: 'sketch1.jpg',
    },
    {
        artName: 'Whimsical Woodwork',
        description: 'Handcrafted wooden sculptures that bring a touch of whimsy to any space.',
        price: 220.00,
        category: 'Sketches',
        creationDate: '2023-01-02',
        listedBy: 'WoodArtisan',
        image: 'sketch2.jpg',
    },
    {
        artName: 'Ethereal Elegance',
        description: 'An ethereal digital artwork that blends fantasy and elegance seamlessly.',
        price: 150.00,
        category: 'Painting',
        creationDate: '2023-02-20',
        listedBy: 'DigitalDreamer',
        image: 'painting4.jpg',
    },
    {
        artName: 'Rustic Realism',
        description: 'Realistic paintings capturing the rustic beauty of rural landscapes.',
        price: 300.00,
        category: 'Painting',
        creationDate: '2022-11-05',
        listedBy: 'RuralRealist',
        image: 'painting5.jpg',
    },
    {
        artName: 'Cinematic Splendor',
        description: 'Photographic prints capturing cinematic moments from around the world.',
        price: 200.00,
        category: 'Sculptures',
        creationDate: '2023-03-05',
        listedBy: 'CinephileShutterbug',
        image: 'sculpture2.jpg',
    },
    {
        artName: 'Whispering Winds',
        description: 'Abstract paintings inspired by the whispers of the wind through nature.',
        price: 160.00,
        category: 'Painting',
        creationDate: '2023-01-28',
        listedBy: 'NatureWhisperer',
        image: 'painting7.jpg',
    },
    {
        artName: 'Cerulean Serenade',
        description: 'A ceramic sculpture in serene shades of blue, evoking a calming melody.',
        price: 450.00,
        category: 'Sculpture',
        creationDate: '2022-12-10',
        listedBy: 'CeramicArtisan',
        image: 'sculpture3.jpg',
    },
    {
        artName: 'Galactic Vision',
        description: 'Digital art exploring galactic landscapes and cosmic visions.',
        price: 180.00,
        category: 'Sketches',
        creationDate: '2023-02-15',
        listedBy: 'CosmicDreamer',
        image: 'sketch3.jpg',
    },
    {
        artName: 'Enchanting Engravings',
        description: 'Intricate engravings on various materials that enchant the observer.',
        price: 250.00,
        category: 'Sculpture',
        creationDate: '2023-03-20',
        listedBy: 'EngravingArtisan',
        image: 'sculpture4.jpg',
    },
    {
        artName: 'Vibrant Vistas',
        description: 'Paintings bursting with vibrant colors, depicting scenic landscapes.',
        price: 280.00,
        category: 'Painting',
        creationDate: '2023-01-12',
        listedBy: 'ColorfulCanvas',
        image: 'painting6.jpg',
    },
    {
        artName: 'Whimsical Watercolors',
        description: 'Delicate watercolor paintings that bring whimsy and charm to any space.',
        price: 130.00,
        category: 'Painting',
        creationDate: '2022-12-28',
        listedBy: 'WatercolorDreamer',
        image: 'painting8.jpg',
    },
    {
        artName: 'Astral Abstractions',
        description: 'Abstract digital artworks inspired by the astral realm and cosmic energies.',
        price: 200.00,
        category: 'Sketches',
        creationDate: '2023-02-28',
        listedBy: 'AstralArtisan',
        image: 'sketch4.jpg',
    },
    {
        artName: 'Rustic Reflections',
        description: 'Photographic prints reflecting the rustic charm of countryside life.',
        price: 150.00,
        category: 'Sketches',
        creationDate: '2023-03-15',
        listedBy: 'RuralExplorer',
        image: 'sketch5.jpg',
    },
    {
        artName: 'Celestial Ceramics',
        description: 'Ceramic sculptures inspired by celestial bodies and cosmic aesthetics.',
        price: 350.00,
        category: 'Sculpture',
        creationDate: '2023-01-20',
        listedBy: 'CelestialArtisan',
        image: 'sculpture5.jpg',
    },
    {
        artName: 'Mystical Murals',
        description: 'Large-scale murals that transport observers to mystical realms.',
        price: 500.00,
        category: 'Sculpture',
        creationDate: '2022-11-15',
        listedBy: 'MuralistMaster',
        image: 'sculpture6.jpg',
    }
];